### ISSUE TITLE
Remove all hard-coded constants from utility files

### ISSUE THREAD

**Issue by fletchapin** [AguaClara/aide_design#12]
We need to go through physchem and other utility files and ensure that any constants used in those files are not hard-coded in but instead reference expert_inputs or materials_database. For example RATIO_VC_ORIFICE is defined as 0.62 in physchem but instead it should be defined as exp.RATIO_VC_ORIFICE to maintain dependency

**Comment by ethan92429** [comment]
This is a fine thing to do. You can automate the process by running pylint... 'linting' code refers to running an automated linter through it that can identify common problems in style
