### ISSUE TITLE
DiamFractal is mislabeled

### ISSUE THREAD

**Issue by monroews** [AguaClara/aide_design#13]
floc_model.py has 
DiamFractal is not a diameter, it is a dimension. It should be labeled as DimFractal.
https://en.wikipedia.org/wiki/Fractal_dimension

**Comment by fletchapin** [comment]
@monroews Zoe and I just went through floc_model.py and changed DIAM_FRACTAL. We don't know what some of the functions are supposed to do, so we left the doc strings for those blank and were hoping you could help complete them
