### ISSUE TITLE
Incorrect functions

### ISSUE THREAD

**Issue by juanchon998** [AguaClara/aide_design#15]
Within physchem, there are two functions that are not correct. 

re_pipe(FlowRate, Diam, Nu): 
In the 'return' line, the diameter should be squared, but it is not.

headloss_manifold(FlowRate, Diam, Length, KMinor, Nu, PipeRough, NumOutlets): 
This function does not work. I'm fairly sure this is because the unit wraps for flow are length**2/time instead of length**3/time, but I could be wrong.

**Comment by ethan92429** [comment]
@juanchon998 Feel free to fix it and send a pull request. If you need help with this, let me know. If you fix it, ideally you'd write a test function that would pass with the new fix.

**Comment by ethan92429** [comment]
Closed by accident! Let me know if you need help with this. A lot of the steps are detailed in the aide_tutorial first contribution tutorial on the aide_tutorial wiki

**Comment by juanchon998** [comment]
I'll look into it to see if I can fix it! I'll let you know if I need help.
Thanks!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ethan92429** [comment]
@juanchon998  in this commit: cd8a0445de0f5f03fb711682c84e9ab809ac1a3e you changed the whole file (well, git thinks you did...) My guess is this is a problem with the way you uploaded the file. How did you do this? I'm reluctant to commit something that shows incorrect changes (as in it shows you deleted and then added lines that you didn't change/touch at all) My guess is this is the [problem](https://stackoverflow.com/questions/19593909/git-diff-sees-whole-file-as-changed-when-its-not) And the solution (I hope) is to use a proper text editor to change the files. Please let me know how you did this!

**Comment by juanchon998** [comment]
Hello Ethan! I cloned aide_design to GitHub Desktop, then opened
physchem.py through spyder. I made the changes (I didn't delete any lines)
and saved the file. I then uploaded the new, changed file to the 0.0.5
branch on github.com. This was all on Sunday

Yesterday I realized one of my two changes was actually incorrect, so I
went back and did the same thing again: opened physchem through spyder,
made the change, and reuploaded the file to github.com.

Let me know if you need more details, my apologies for handling this
clumsily!
Juan



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
