### ISSUE TITLE
Ensuring constants are defined in the correct files

### ISSUE THREAD

**Issue by zam7** [AguaClara/aide_design#22]
Should we add constants (like width of PVC sheet for baffle) to the materials database file?

**Comment by fletchapin** [comment]
Examples of constants include:
HS_min, HS_max, width_PVC_sheet, min_width_floc

**Comment by ethan92429** [comment]
I don't like adding non-fundamental constants to AIDE design in general. I think things that are plant specific, such as widths of materials should be updatable in the templates. You could specify them in the relevant unit process's template.... how does that sound?
