### ISSUE TITLE
The YAML file doesn't update down the hierarchy

### ISSUE THREAD

**Issue by fletchapin** [AguaClara/aide_design#23]
e.g. in the plantwide YAML q_plant and temp are user defined inputs. How do we get these updates to bubble down different unit processes?
<img width="248" alt="screen shot 2018-02-05 at 2 25 09 pm" src="https://user-images.githubusercontent.com/17417538/35824295-73d92aaa-0a80-11e8-9375-a8f169b340fa.png">
<img width="854" alt="screen shot 2018-02-05 at 2 25 35 pm" src="https://user-images.githubusercontent.com/17417538/35824297-758b5058-0a80-11e8-9d0d-5f5c5bf93c86.png">

**Comment by ethan92429** [comment]
Apparently when using the macro to include the file, the context has to be passed explicitly. If you don't wrap the include statement within a macro (which is like a function), it should work fine.
