### ISSUE TITLE
Accessing data from the YAML file

### ISSUE THREAD

**Issue by fletchapin** [AguaClara/aide_design#25]
Is there a way to access data from the YAML file using Jinja2? When we were working on the flocculator template we noticed that the approach below didn't work to access the flocculator flow rate.
<img width="657" alt="screen shot 2018-02-07 at 2 54 11 pm" src="https://user-images.githubusercontent.com/17417538/35938462-29e3905a-0c17-11e8-87be-ae4468577291.png">
However, when q is set then it works. Our question is whether there's a way to access q from floc_tank without using {% set q =  %} so that we wouldn't have to worry about using {% set q =  %} in both the floc and sed templates and having to keep the two flow rates differentiated, e.g. floc_tank.hp.q (this didn't work as well).
<img width="655" alt="screen shot 2018-02-07 at 2 53 59 pm" src="https://user-images.githubusercontent.com/17417538/35938465-2adfdd2e-0c17-11e8-85b1-77ffac9ba1c8.png">

**Comment by ethan92429** [comment]
Jinja doesn't know or care about what the file is that it is modifying. It just throws text together. However, if you rendered the template, then you could call pyyaml in the outer template to parse the inner template. This could be used to intermediately build the outer template from increasingly completed inner templates. So for instance, you may get the manufactured sheet width with a pyyaml call, and then set the actual sheet length again. I think an example would help. I'll throw one up tomorrow.

**Comment by zam7** [comment]
@ethan92429 did you put up an example for us? And if so, where is it?

**Comment by ethan92429** [comment]
@zam7 Hi Zoe, I worked a little bit on it. The idea is simple: just use pyyaml directly in jinja to load the constants of the nested components... this would look like {{ floc_tank = yaml.load(floc_tank.yaml) }}. However, it's a bit more complicated a setup than that... so you'll probably want to make your own function that processes inner components. Unfortunately, things for Rose and I are a bit up in the air right now and I won't get around to this until next week. Give it a shot and let me know how far you get!

**Comment by zam7** [comment]
@ethan92429 ok, sounds good! Good luck figuring your stuff out! :)

**Comment by fletchapin** [comment]
@ethan92429 When you were in Ithaca, we talked about explicitly passing variables in and out of templates. I was wondering if you made any progress on how we could do this?

**Comment by ethan92429** [comment]
Yup! I'm making a little command line tool that will let you run your templates and employ an MVP of a 'template import protocol'. it'll look something like: `set sed_tank = aide_render.render(sed_tank.yaml)["variables"]` sorry about how long it's taken! I'm hoping it'll be ready by wednesday.

**Comment by fletchapin** [comment]
This is now possible with aide_render. For example:
```
{% macro test(comp_inputs) %}
  {% assert_inputs(comp_inputs, types dict) %}
  {% set self = render_constants("test.yaml") %}
{% endmacro %}
```
