### ISSUE TITLE
Create an error message when using deprecated names such as expert_inputs.py instead of constants.py

### ISSUE THREAD

**Issue by fletchapin** [AguaClara/aide_design#30]
expert_inputs.py has become constants.py

added:
optional_inputs.py

Need to write code that allows exp_inputs to be used if called (by making the current constants.py available to it, but send error messages to let the user know that the exp_inputs it is deprecated.

**Comment by zam7** [comment]
@ethan92429 Where should we be writing this code? Should it be added to play.py or somewhere else to make sure that the warning is triggered correctly?

**Comment by ethan92429** [comment]
@AguaClara/aide_design to warn when something is imported that shouldn't be, you need to put in a deprecation warning. [Here's a little tutorial on it](http://www.lesinskis.com/python_deprecation_tutorial.html). Basically, just add this code whenever you want to push a warning:
```python
import warnings
warnings.warn(This is the deprecation method",DeprecationWarning )
```

Now put this at the top of the expert_inputs.py, or whatever file you are deprecating.

**Comment by zam7** [comment]
We added the warning to expert_inputs with an explanation that constants.py and optional_inputs.py will be used instead. This was tested and when the aide_design.play package imports (or when just expert_inputs is imported), the error message is shown.
