### ISSUE TITLE
LFOM orifice array design

### ISSUE THREAD

**Issue by zam7** [AguaClara/aide_design#32]
How to determine the spacing between orifices? Is it based on the maximum orifice per row calculation that is in the Mathcad files?

We are making 30 rows that will either be populated with the number of orifices for that row, or with 0 orifices. How do we know which rows (of the 30 possible) should be populated (depending on how many overall rows we want)

**Comment by zam7** [comment]
Mathcad uses a S minimum of 1 cm

**Comment by zam7** [comment]
1) Fix the number of rows function
2) Figure out if we actually need 4, 5, 8, and 10 row options - determine that by plugging in different flow rates and seeing what we actually need

Actual design:
3) Calculate the number of rows needed for q_plant. Figure out which of the 40 need to be populated.
4) Determine the number of orifices for each row
5)  Figure out geometry of the orifice array - will need to take into account orifice offset from even and odd orifice numbers. 
6) Using an origin of (0,0) for the first orifice on the first row, report to template team
- offset of the location of the first orifice of each row
- height of each row
- number of orifices in each row

**Comment by monroews** [comment]
Here is the code in Mathcad.
I did find that for flowrates less than 20 L/s it was 8 rows. But ideally this would be calculated using an equation. See below
![image](https://user-images.githubusercontent.com/28540907/36695012-fefc80c6-1b0d-11e8-8ca4-0722a0eb9ca7.png)

![image](https://user-images.githubusercontent.com/28540907/36694988-ee79f760-1b0d-11e8-8e7f-6fbf40046f76.png)
