### ISSUE TITLE
Create sed tank python module and YAML template

### ISSUE THREAD

**Issue by fletchapin** [AguaClara/aide_design#35]
Create sed.py which will have all the hydraulic functions necessary to calculate the design parameters in the plant which are needed by Fusion.

Also create an accompanying YAML template which will call sed.py's functions in order to fill in the template parameters.

**Comment by zam7** [comment]
@monroews We are beginning the sedimentation tank design. The width of the sedimentation tank is not currently defined in Python. However, in the 4540 DC and final project from last year, the width of the sed tank is given as a constant of 42 inches because that is the width of the PVC sheet. Is this width that should be defined in our manufacturers_constraints.yaml template?

**Comment by monroews** [comment]
Yes. The plate settler polycarbonate sheets that we are using are 42" wide. This would be an expert input in our old way of defining inputs. It should be relatively easy for someone to change this value.

**Comment by fletchapin** [comment]
@monroews We discussed keeping the length of the sedimentation tank constant and then basing the length of the flocculator channel on that length.

In order to keep the flocculator and sedimentation unit processes rectangular, the flocculator should be the same length as the sedimentation tank plus the inlet and outlet channels. So our question is should we keep the total length of the sedimentation process (e.g. tank + channels) constant so that the flocculator is always the same length, or keep just the length of the tank constant and have the channels (and therefore total length) vary.

**Comment by monroews** [comment]
I think the first question is whether it makes sense to make all of the channels the same size in the flow range from 20 to 60 L/s. I think that might make sense. And then the total length of the sed tanks is a constant and the flocculator length is a constant.

**Comment by zoemaisel** [comment]
@monroews  Using the code that was written for the 4540 final assignment (H2FLows), the total channel width changes from 20 to 60 L/s. The exit channel remains constant around 40 cm but the inlet channel varies from 40 to 70 cm. 

We are unsure if the 4540 code is correct and do not understand why the entrance channel scales up so much while the exit channel does not. We will review the Mathcad code to make sure that this is in fact the case.

**Comment by monroews** [comment]
The design constraints for each channel are different. The inlet channel must have very small pressure recovery (with v^2/2g<<5cm where 5 cm is the head loss through the sed tanks.
The other channels just need to be able to carry the flow without overflowing.
Geometric constraints then tend to set the size of the other channels (min width for the mason, pipe fittings).
Thus it appears that all sed tanks could be made identical if we are willing to have a 20 L/s plant where the channels are 30 cm wider than needed.
I propose that we do exactly that. Make the channels identical for all of these sed tanks from 20 to 60 L/s.

**Comment by fletchapin** [comment]
Ok we will standardize the channel width.

We have another question about the jet reversers and diffusers. Do the diffusers and jet reversers have the same diameter for all flow rates?

**Comment by monroews** [comment]
Diffusers always have the same flow rate as long as the sed tank width and upflow velocity don't change. That means that the diffusers and jet reversers are always the same for all flow rates.

**Comment by fletchapin** [comment]
Done!
