### ISSUE TITLE
Sed Tank Module Function 

### ISSUE THREAD

**Issue by CynthiaTChan** [AguaClara/aide_design#36]
@monroews The MathCad function for determining plate settler modules currently is written so each plant could have different number of plate settlers per module, starting with mod 8 and going up (apparently without end). Is it acceptable to rewrite the function so they are standardized to 10 plate settlers per module, and whatever number of P.S. remaining gets added onto a new module or added to the set of 10?

**Comment by monroews** [comment]
Yes! identical modules for all plants is best. leftovers can be a small
module.

**Comment by fletchapin** [comment]
Ok we will make modules of 10 plates and then one module which has the "leftover" plates at the end.
