### ISSUE TITLE
Plate Settler spacer pipe specification

### ISSUE THREAD

**Issue by CynthiaTChan** [AguaClara/aide_design#37]
@monroews I cannot find documentation on the plate settler spacer pipe specification. In this [file] (https://docs.google.com/spreadsheets/d/1UPWzB1XgeCndprMN8Inm6SqEkhQoMA-GpteLmXRBW5Y/edit#gid=1608333328), on the sed tank sheet, Module_SDRSpacer is reported to be 17 but I am unsure where this comes from.

**Comment by monroews** [comment]
There are relatively few different SDRs available for small pipe sizes. I'd expect that for the plate settlers we use the thinnest wall pipes that is commercially available.
