### ISSUE TITLE
Create BOD (basis of design) file

### ISSUE THREAD

**Issue by fletchapin** [AguaClara/aide_design#38]
@zoemaisel and I think that it would be beneficial to create another module that would be used to separate bases of design from the physical constants which belong in constants.py.

Once bod.py is created, many of the global variables in constants.py would be moved over. For example, the headloss of the sed launder is not a universal constant so it would belong in bod.py not its current location of constants.py

**Comment by ethan92429** [comment]
I think bod might be a confusing name and doesn't conform to the python module naming standards. Maybe design_constants.py makes more sense? 

Also, why make this a separate file? Could instead the sed launder headloss be defined within the sed launder component template? I can imagine there are tradeoffs to having it be separate v. integrated. I think it makes sense to have the variables as 'close' to where their getting used as possible. By close, I mean you should have to navigate to the sed launder component to change the sed launder headloss. Perhaps the concern here is having access to those innermost component constants. To solve this problem, I propose we have two sub-component loading steps. The first can be considered a "dependency free loading" - where we can load anything that doesn't depend on context outside the scope of the template into the current namespace. This is a bit tricky to explain over the issue. But see if you can tell what this code I spent wayyy too long on making does: https://gist.github.com/ethan92429/4efa48f426ec4ecda21e8c961ed1a939
I will hopefully have a better MVP for you soon! sorry for the delay... ☹️
