### ISSUE TITLE
Should temperature be a user input or an optional input?

### ISSUE THREAD

**Issue by fletchapin** [AguaClara/aide_design#40]
@monroews At the moment temperature is an input into many of our flocculator, entrance tank, and sedimentation functions. After looking at the Mathcad code we noticed that the design temperature wasn't defined in expert inputs, but it also didn't appear to be a user input of the old design engine?

Do you think we should simply set the temperature as an optional input or make it a user input?

**Comment by monroews** [comment]
Make temperature be a user input.
