### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by fletchapin** [AguaClara/aide_design#43]
We need to do a number of things involving documentation:
- Update docstrings in functions according to numpy standards
  - This includes doctests
- Add to the docstring at the very top of each unit process script:
  - What goes into the inputs dictionary
    - Include definitions for each parameter similar to those in function docstring
  - What all required user inputs are

**Comment by zoemaisel** [comment]
@ethan92429 We have a style question about documentation for the dictionaries. We have two different ideas for how to do it and want your input!

Option 1: All of the input dictionary contents are defined at the top of the file and are not redefined in the function. 
Example:
![top_file_definition](https://user-images.githubusercontent.com/31140352/37733222-c190dc74-2d1d-11e8-810a-34ef554ed6c3.png)
![screen shot 2018-03-21 at 3 16 53 pm](https://user-images.githubusercontent.com/31140352/37732994-0937d380-2d1d-11e8-8af8-80ee19c2fba6.png)

Option 2: Any of the input dictionary contents that are used in a function are defined within the function docstring and are not defined at the top of the file. 
Example:
![screen shot 2018-03-21 at 3 20 23 pm](https://user-images.githubusercontent.com/31140352/37733023-1afff6c4-2d1d-11e8-8f18-92a6c79e9284.png)

Do you have guidance/preference for how we move forward? We think it would be easier for us to go with Option 1 to avoid writing the same thing many times, and we think that defining it once at the top of the file will be sufficient to allow someone to figure out whatever they need.

**Comment by ethan92429** [comment]
@zoemaisel Hmm... I wonder if we should still be using functions such as width_stout? Would it be possible to instead write only one function (call it lfom()) that takes in a dict and goes through the whole LFOM design process. Imagine this function lives at the top of the file. It is the "gold standard" for thoughts on how to design an LFOM. All other functions in the module are used to do its bidding (don't worry about re-doctesting or modifying the other functions.) Look at this bakery example, for instance:

```python
def pie(pie):
  """Makes a pie from a pie definition. 

  Parameters
  -----------
  pie
    a dict including at the minimum: pie_filling, pie_shape, pie_size
  
  Returns
  --------
  dict
    a pie dict that is filled in. This means all the ingredients are defined, the chef who made it is
    recorded... maybe even the restaurant it was made in is recorded!
  """
  # Add things to the pie as needed:
  pie['ingredients'] = get_ingredients(pie['filling'])
  pie['chef'] = find_a_chef()
  return pie
```

In this example pie uses multiple already existing functions to fill it in. This example is screaming to be turned into an OO example with a pie class. But I think that would be a tangent and we can do it without classes for now. And we can convert this to a class later on (next semester). Does this make sense? You can see how with this function, you only specify one 'designer' function per unit process, so it only would make sense to document the one large function. Thoughts on this? From your perspective, would it be easy enough to implement?

**Comment by zoemaisel** [comment]
We changed to a class method and this question is no longer directly applicable.
