### ISSUE TITLE
n_lfom_orifices function lfom_dict_test.py is not working

### ISSUE THREAD

**Issue by anthonyverghese** [AguaClara/aide_design#49]
Here is the error:
![image](https://user-images.githubusercontent.com/20823341/38518832-0bb7ff7e-3c0c-11e8-9452-3f2dc55eb744.png)

There seems to be an issue with the n[i] = ... statement, but I could not figure out how to fix it. I don't see how this is invalid syntax.

**Comment by fletchapin** [comment]
There was a missing parenthesis on the line above which caused the error. Fixed now
