### ISSUE TITLE
n_lfom_orifices_fusion function: not able to run an example

### ISSUE THREAD

**Issue by anthonyverghese** [AguaClara/aide_design#50]
Here is the error I get when I try running the function with some example inputs: 
![image](https://user-images.githubusercontent.com/20823341/38520583-2b531e5e-3c11-11e8-87b0-f53ac593bf21.png)

I'm not sure what this error is and could not figure it out when searching stuff up online.

**Comment by fletchapin** [comment]
The issue was actually with the units of a different function in lfom_dict_test. It's been fixed now
