### ISSUE TITLE
drain_OD function in ent_tank_dict_test.py is not working

### ISSUE THREAD

**Issue by anthonyverghese** [AguaClara/aide_design#52]
I get the following error when I try doing shift+enter on the function: 
![image](https://user-images.githubusercontent.com/20823341/38771656-bf783b1e-3ff4-11e8-8891-5a942253a58d.png)

I was not sure how to fix this issue

**Comment by fletchapin** [comment]
I just checked this function and it's running in the filter_design branch. In the screenshot there's a ```+``` missing after ```con.K_MINOR_PIPE_ENTRACNE``` but it was there on my branch.
