### ISSUE TITLE
num_plates_ent_tank function in ent_tank_dict_test.py not working

### ISSUE THREAD

**Issue by anthonyverghese** [AguaClara/aide_design#53]
The error I get when I do shift+enter on the function: 
![image](https://user-images.githubusercontent.com/20823341/38771713-e91a30de-3ff5-11e8-8837-a23516932ddd.png)

I'm not sure why this issue is coming up. It should be trivial, though.

**Comment by fletchapin** [comment]
@anthonyverghese I think you forgot run ```from aide_design.play import *``` so that ```u``` was undefined. It's working on my computer
