### ISSUE TITLE
Issue with ID_exit_man in sed_tank_dict_test

### ISSUE THREAD

**Issue by DeelanChiu** [AguaClara/aide_design#57]
In ID_exit_man there appears to be a denominator missing, since right now there is just 1/ for one of the numbers.

![image](https://user-images.githubusercontent.com/19920359/38830712-35879524-418b-11e8-8385-89a6b7c55f5b.png)

**Comment by monroews** [comment]
Here is the Mathcad code
![image](https://user-images.githubusercontent.com/28540907/38833329-2f0f4392-4193-11e8-86f7-1a721b4a32fa.png)

**Comment by zoemaisel** [comment]
I fixed the issue and added the test case for the function!
