### ISSUE TITLE
Issue with w_diffuser_inner in sed_tank_dict_test

### ISSUE THREAD

**Issue by DeelanChiu** [AguaClara/aide_design#58]
In the return statement of this function, the numpy statement that tries to use u.inch throws an error about not being able to compare Quantity with numpy.ndarray

![image](https://user-images.githubusercontent.com/19920359/38831910-dc67562e-418e-11e8-9a72-ae34be506cca.png)

![image](https://user-images.githubusercontent.com/19920359/38831986-18cb23e8-418f-11e8-9f63-11190782a7dc.png)

**Comment by zoemaisel** [comment]
Fixed the two functions w_diffuser_inner_min and w_diffuser_inner
