### ISSUE TITLE
sed_tank_dict_test broken functions

### ISSUE THREAD

**Issue by DeelanChiu** [AguaClara/aide_design#61]
A lot of the functions fail since there is the following error w_diffuser_outer
![image](https://user-images.githubusercontent.com/19920359/38954561-f43cf294-431f-11e8-87a6-fdd1218bbaba.png)

The following functions are not working in sed_tank_dict_test.
w_diffuser_outer
L_diffuser_outer
L_diffuser_inner
q_diffuser
vel_sed_diffuser
vel_inlet_man_max
n_tanks
L_channel
D_exit_man_orifice
L_sed_plate

**Comment by zoemaisel** [comment]
Fixed all functions so they run now
