### ISSUE TITLE
Change floc.py functions to reflect to class methods

### ISSUE THREAD

**Issue by zoemaisel** [AguaClara/aide_design#62]
Use keyword arguments for any function inputs that we don't want students to have to change or define

**Comment by ethan92429** [comment]
Note that the classes can override the method arguments if necessary.

**Comment by zoemaisel** [comment]
The following attributes are used in floc.py; some of them will be designated as keyword arguments. @fletchapin do you agree with the designations I've made?

L_ent_tank_max : float <---- keyword argument
    The maximum length of the entrance tank

L_sed : float <---- keyword argument
    The length of the sedimentation tank

hl : float
    Headloss through the flocculator

coll_pot : int
    Desired collision potential in the flocculator

freeboard: float <---- keyword argument
    The height between the water and top of the flocculator channels

ratior_HS_min : int <---- keyword argument
    Minimum allowable ratio between the water depth and edge to edge distance
    between baffles

ratio_HS_max : int <---- keyword argument
    Maximum allowable ratio between the water depth and edge to edge distance
    between baffles

W_min_construct : float <---- keyword argument
    Minimum width of a flocculator channel based on the width of the human hip

baffle_thickness : float <---- keyword argument
    Thickness of a baffle

**Comment by zoemaisel** [comment]
Problems I'm running into (notes for myself for now):
- width_HS_min function gives different output from previous calculation with dict method
- width_floc_min function does not work with optional keyword arguments but works when all inputs are detailed
