### ISSUE TITLE
Problems with Flocculator class

### ISSUE THREAD

**Issue by fletchapin** [AguaClara/aide_design#66]
We noticed some issues with the Flocculator class while testing.
- Num_Exit < Num_Inlet
  - This shouldn't be the case
- Width > minimum width for constructability
- Update Bottom and Top Baffles Assembly
  - They have some info like ```ent_tank_length``` missing
- Nested classes aren't showing up in the YAML
  - They need to follow the ```dict(vars(Class))``` approach

**Comment by fletchapin** [comment]
Completed the last two bullets. Still remaining is:
- Num_Exit < Num_Inlet
  - This shouldn't be the case
- Width > minimum width for constructability

**Comment by monroews** [comment]
What is the flow rate where this happens? As we move toward higher G and lower volume flocculators the problem with our two channel flocculator design becomes apparent.  The [20 L/s plant](http://designserver.cee.cornell.edu/Designs/EtFlocSedFi/7667/20Lps/Index.html) doesn't seem to have run into this problem and I believe that is the lowest flow rate you are designing right now.

I'd propose simply keeping the minimum width as an absolute minimum width and leaving more space for the contact chamber between the entrance tank and the flocculator.
