### ISSUE TITLE
push this to a package as soon as possible

### ISSUE THREAD

**Issue by monroews** [AguaClara/aide_design#76]
My understanding is that the aide package is pretty far behind the master branch. As I'm working on the textbook that means that some of the constants I want to access will no longer be in expert inputs after the new code is published. So it would be awesome if a new version of the aide package could be released soon.

**Comment by fletchapin** [comment]
@monroews I'll be finalizing the code this weekend and then we can merge all of our changes from the semester into master and publish the package via pip.

Do you want to meet sometime next week to go over all the changes that were made?

**Comment by monroews** [comment]
I'd suggest that somewhere with the new release you publish a list of the major changes. That way we will have a reference when we are updating the CEE 4540 assignments.
Let's meet too!

**Comment by ethan92429** [comment]
We're up to (0.0.10)[https://pypi.org/project/aide_design/]! It's all automated... so when things are pushed to master and then tagged, if the tests pass, we automatically push to pypi! Feel free to update and test it out... `pip install -U aide_design --user`

**Comment by ethan92429** [comment]
If you'd like, we could all meet at the standard aide_design meeting time... 2:30 on Tuesday I believe!

**Comment by ethan92429** [comment]
As for a list of major changes, @fletchapin [here is a compare from version 0.0.4 to 0.0.11](https://github.com/AguaClara/aide_design/compare/0d2ddab2c8f0e5379071ac9e6000ed94356203dc...master) for assembling a changelist.

**Comment by monroews** [comment]
Below is what I got in the anaconda cmd window.
It doesn't appear to have upgraded.
I restarted atom and I don't yet see aide_design.constants. I only see aide_design.expert_inputs

(C:\Users\mw24\Anaconda3) C:\Users\mw24>pip install -U aide_design
Collecting aide_design
  Downloading https://files.pythonhosted.org/packages/57/a6/e98910cf938651d75d782750a2811d252c49a0b951d3fa0c98c7f8c17974/aide_design-0.0.11.tar.gz (50kB)
    100% |████████████████████████████████| 51kB 409kB/s
Requirement not upgraded as not directly required: pint in c:\users\mw24\anaconda3\lib\site-packages (from aide_design) (0.8.1)
Requirement not upgraded as not directly required: numpy in c:\users\mw24\anaconda3\lib\site-packages (from aide_design) (1.12.1)
Requirement not upgraded as not directly required: pandas in c:\users\mw24\anaconda3\lib\site-packages (from aide_design) (0.20.1)
Requirement not upgraded as not directly required: matplotlib in c:\users\mw24\anaconda3\lib\site-packages (from aide_design) (2.0.2)
Collecting scipi (from aide_design)
  Could not find a version that satisfies the requirement scipi (from aide_design) (from versions: )
No matching distribution found for scipi (from aide_design)

(C:\Users\mw24\Anaconda3) C:\Users\mw24>

**Comment by ethan92429** [comment]
This is great - the only thing that the tests don't test (deployment/ dependency management through setuptools) ends up failing because of a silly typo (scipi instead of scipy). I even pushed a fix to this two days ago but just didn't tag a new release yet. Should be sent out as of now (try upgrading again)
